# Este flujo de trabajo usa acciones que no GitHub no certifica.
# Estas las proporcionan entidades terceras y las gobiernan
# condiciones de servicio, políticas de privacidad y documentación de soporte
# en línea.

# GitHub recomienda anclar acciones a un SHA de confirmación.
# Para obtener una versión más reciente, debes actualizar el SHA.
# También puedes hacer referencia a una etiqueta o rama, pero la acción puede cambiar sin ninguna advertencia.

name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2019, macos-10.15 ]
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: wheels-app-backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v1
        with:
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: build